create database case_study1

use case_study1

select * from fact
select * from product
select * from location

--Task to be performed

--1)Disply number of states that is present in location table?

select count(distinct state) as count_of_state
from location


--2) How many products are of regular type ?

select count(*) as count_of_regular from product
where type = 'regular'

--3) How much spending has been done on marketing 
--of product id 1

select * from fact

select sum(marketing) as total_marketing
from fact
where productid=1

--4) What is the minimum sales of a product ?

select min(sales) as [min value] from fact

--5) Display max Cost of Good Sold(COGS).

select  max(COGS) as [max value]
from fact


--6) Display the Details of the productid where
--product type is coffee

select *  from product
where product_type='coffee'



--7) Display the details where total_expenses 
--is greater than 40.

select total_expenses from fact
where total_expenses>40

--8) What is the average sales in Area_Code 719 ?
select * from fact

select avg(sales) as [avg sales] from fact
where area_code = 719



--9) Find out the total profit generated by
--Colorado state.

select sum(profit) as profit_of_Colorado_state 
from fact f
inner join 
location l
on
l.area_code= f.area_code
where state = 'Colorado'



--10) Display the average inventory for each product id.

select avg(inventory) as avg_inventory,productid
from fact
group by productid
order by productid

--11) Display state in a sequential order in
--a location table.

select distinct state from location
order by state asc


--12) Display the average budget margin of the store 
--where average budget margin should be
--greater than 100.

select * from fact


select avg(budget_margin) as avg_budget,productid
from fact
group by productid
having avg(budget_margin)>100

--13) What is the total sales done on date 2010-01-01

select sum(sales) as total_sales
from fact
where date='2010-01-01'



--14) Display the average total 
--expense of each product id on individual date

select date,productid,avg(total_expenses) as avg_expenses
from fact
group by productid,date
order by date

--15) Display the table with the following attributes such as
--Date, productid, product_type, product, Sales, profit, state, area_code


select f.date,f.productid,p.product_type,p.product,f.sales,f.profit,l.state,l.area_code
from fact f 
inner join
product p
on
p.productid=f.productid
inner join
location l
on
l.area_code = f.area_code

--16) Display the rank without any gap to show 
--the Sales wise rank.

select sales,dense_rank() over(order by sales asc) as rank_sales
from fact


--17) Find the State wise Profit and Sales.

select l.state,sum(f.profit) as profitamt,sum(sales) as salesamt
from fact f
inner join
location l
on
l.Area_Code=f.Area_Code
group by l.state


--18) Find the State wise Profit and Sales along with the Product Name.

select l.State,p.Product,sum(profit) as profitvalue,sum(sales) as salesvalue
from fact f
inner join
location l
on
l.Area_Code=f.Area_Code
inner join
product p
on
p.ProductId=f.ProductId
group by l.State,p.Product

--19) If there is an increase in sales of 5%. Calculate the increased sales.

select * from fact

select sales,sales*1.05 as incresedsales from fact

--20) Find the maximum profit along with the Product id and Product Type.

select max(f.profit) as profitvalue,p.ProductId,p.Product_Type
from fact f
inner join
product p
on
p.ProductId=f.ProductId
group by p.ProductId,p.Product_Type

--21) Create a Stored Procedure to fetch the result according to
--the product type from Product.

create procedure p_type(@proc_type varchar(30))
as
begin
select * from Product
where Product_Type=@proc_type
end

exec p_type 'coffee'
exec p_type @proc_type ='tea'

--22) Write a query by creating a condition in which if the total expenses is 
--less than 60 then it is a profit or else loss.

select Total_Expenses,iif(total_expenses<60,'profit','loss') as profitvalue
from fact

--case
--when totalexpenses<60 then 'profit'
--else
--'loss'

--23) Give the total weekly sales value with the Date and productid details. 
--Use roll-up to pull the data in hierarchical order.

--grad total,subtotal 

select date,productid,sum(sales) as totalsales
from fact
group by date,productid with rollup

SELECT Date,ProductId, SUM(sales) as 'Total Sales'
FROM fact
GROUP BY ROLLUP(ProductID), Date;


--24) Apply union and intersection operator on the tables
--which consist of attribute area code.

select area_code from fact
union
select area_code from Location

select area_code from fact
union all
select area_code from Location

select area_code from fact
Intersect
select area_code from Location

--25) Create a user-defined function for the product table to fetch a particular product type based
--upon the user�s preference.

create function fn_type(@prod_type varchar(20))
returns table
as
return
select * from product
where Product_Type=@prod_type

select * from dbo.fn_type ('coffee')

--26) Change the product type from coffee to tea where product id is 1 and undo it.
begin transaction

update Product
set Product_Type='tea'
where ProductId=1 

rollback transaction

select * from Product

--27) Display the Date, productid and sales where total expenses 
--are between 100 to 200.


select date,productid,sales,Total_Expenses from fact
where Total_Expenses between 100 and 200

--28) Delete the records in the product table for regular type.

delete
from Product
where Type='regular'

select * from Product

--29) Display the ASCII value of the fifth character from the column product.

select ASCII('A')

select * from Product

select Product,SUBSTRING(product,5,1),
ASCII(SUBSTRING(product,5,1))
from Product
